### PR TITLE
Krater

### PR DESCRIPTION
**Pull request by danik4985**
Turn the catterpillar in the readme into Krater by giving him a cigarette! krater

This is very important for the future and growth of Aliucord

### CODE REVIEW

**Review by Vendicated — APPROVED** [review]

**Review by zt64 — APPROVED** [review]

**Review by C10udburst — APPROVED** [review]

**Review by ItzOnlyAnimal — APPROVED** [review]
merge NOW

**Review by taskylizard — APPROVED** [review]
need more

**Review by DiamondMiner88 — APPROVED** [review]
if krater has a million fans im one of them
if krater has 0 fans then I am no more 
if krater has 1 fan that fan is me
if the world is against krater then I'm against the world

**Comment by Ali00035v2** [comment]
**ali**ucord

**Comment by Ali00035v2** [comment]
nice pr btw

**Review by Ali00035v2 — APPROVED** [review]

**Review by wingio — APPROVED** [review]

**Comment by taskylizard** [comment]
W

**Pull request merged**
