### PR TITLE
use translations where possible

### PR DESCRIPTION
**Pull request by C10udburst**
Use translated string for Aliucord settings

Some examples:

English:
```lua
Settings -> Settings
Uninstall -> Delete
Crashes -> Crash Details
Open Debug log -> Debug
Updater -> Update
```

Polish:
```lua
Settings -> Ustawienia
Uninstall -> Usuń
Crashes -> Szczegóły awarii
Open Debug log -> Debuguj
Updater -> Aktualizacja
```

German:
```lua
Settings -> Einstellungen
Uninstall -> Löschen
Crashes -> Absturzdetails
Open Debug log -> Debuggen
Updater -> Aktualisieren
```

### CODE REVIEW

**Comment by GangsterFox** [comment]
I dont exactly like the translation for German "Debuggen"
It sounds better to say "Debug Protokolle öffnen"
Or just for ease (and a lot of Germans should understand the word Log) "Debug Logs öffnen"

**Comment by wingio** [comment]
ignore fox he doesn't know how translation works in android

**Comment by GangsterFox** [comment]
I wish android was not so retarded

**Comment by OmegaSunkey** [comment]
finally translations to spanish became tru

**Comment by C10udburst** [comment]
yes

**Comment by C10udburst** [comment]
so uhh

https://user-images.githubusercontent.com/18114966/162830499-fcdddbe6-255a-4f58-bb88-4967fa58fc77.mp4

**Comment by rushiiMachine** [comment]
if this would ever to be added it's more likely some sort of custom translations with crowdin would be used

**Pull request closed without merging**
