### PR TITLE
Add HttpUtils Request/Response classes to ease making Http Requests

### PR DESCRIPTION
**Pull request by Vendicated**
Adds RequestBuilder kinda similar to the Powercord one to ease sending HttpRequests. Does not have querystring support yet and I also haven't tested it yet so its still a draft

### CODE REVIEW

**Comment by Swishilicous** [comment]
You should also make methods with the auth token as the authorization header like powercord so calling direct http requests to discord is easier.

**Review by Juby210 — COMMENTED** [review]
Is this ready to merge or still `draft`?

**Comment by Vendicated** [comment]
i think it has everything thats needed now, just have to test to make sure it's all working alright

**Comment by Vendicated** [comment]
Ok ready for merge now, tried Json GET and POST and both worked well. I changed the updater to using the new methods

This should not break plugins as i left the methods in and marked them as deprecated, or should we just remove them?

**Review by Juby210 — APPROVED** [review]

**Pull request merged**
