### PR TITLE
fix: user settings parser race condition

### PR DESCRIPTION
**Pull request by DiamondMiner88**
funny discord with the parser race condition bug

### CODE REVIEW

**Review by ItzOnlyAnimal — APPROVED** [review]
:trollface:

**Comment by Vendicated** [comment]
Discord loves having insane shitcode :trollface:

**Comment by AndyG** [comment]
@Vendicated my bad

**Comment by Vendicated** [comment]
kjskasjas IM SORRY andy i didnt mean it 😭

**Comment by AndyG** [comment]
@Vendicated lmao it's all love bro. hundreds of thousands of lines of code, this is not the first insane shit I've mistakenly written and it won't be the last :) have a good day!

**Comment by Vendicated** [comment]
Hey @AndyG, seems like you're working on Discord again? thats really nice to see

Looks like a very similar issue to this one is happening again which breaks connecting to the gatway on old discord versions:
Instead of the old
```json
{"t":null,"s":null,"op":10,"d":{"heartbeat_interval":41250,"_trace":["[\"gateway-prd-us-east1-b-p8ff\",{\"micros\":0.0}]"]}}
``` 
the gateway is now sending
```json
{"d":{"_trace":["[\"gateway-prd-us-east1-c-96qc\",{\"micros\":0.0}]"],"heartbeat_interval":41250},"op":10,"s":null,"t":null}
```

which leads to
```
03-04 23:44:17.139 23286 23452 E Discord : Unable to parse model.
03-04 23:44:17.139 23286 23452 E Discord : Metadata:
03-04 23:44:17.139 23286 23452 E Discord : kotlin.UninitializedPropertyAccessException: lateinit property opcode has not been initialized
```
in
image
because d now comes before op so opcode isnt initialised yet

since you guys fixed the issue the last time, i figured it might be worth a shot to let you know to maybe get this fixed for users of the old version? seems in discord's interest to retain even those users

**Pull request merged**
