### PR TITLE
fix borked plugin cards in amoled

### PR DESCRIPTION
**Pull request by Swishilicous**
i also may have changed the search input a little bit because i think the old version looked a bit off but you can change it back if you want

### CODE REVIEW

**Comment by WinstonSepruko** [comment]
> fix borked cards in amoled

omg thanks finally

**Comment by MulverineX** [comment]
Wonderful, I'm guessing this fixes them for Juby's LSPosed Themer too right?

**Comment by Swishilicous** [comment]
I would have no idea but I assume his themer can hook into the fields I referenced in the commit.

**Comment by MulverineX** [comment]
Oh it still doesn't then, dang

**Comment by Juby210** [comment]
This PR is still not merged because it fixes plugin cards in amoled by breaking them on all other themes.

**Pull request closed without merging**
