### PR TITLE
add SettingsPage#removeScrollview, fixes plugin page lag

### PR DESCRIPTION
**Pull request by mantikafasi**
which fixes lag in plugins page while opening
code is a cursed a bit but idk any better options since if I patch main class what adds this discord pages may get broken too

### CODE REVIEW

**Comment by Vendicated** [comment]
you will make code not shit and not use profanity

**Comment by mantikafasi** [comment]
@Vendicated review or you will get diarrhea

**Comment by Vendicated** [comment]
Add javadoc

**Comment by mantikafasi** [comment]
done

**Comment by mantikafasi** [comment]
ven merged my pr, I think I'm going to cry.

**Comment by YoussefBedwarspro** [comment]
Aliucord I don't need you anymore

**Comment by YoussefBedwarspro** [comment]
Although it's a little rude to say that.
 (˘･_･˘)

**Pull request merged**
