### PR TITLE
Fix NPE when accessing logger in PatcherExtensions

### PR DESCRIPTION
**Pull request by zt64**
Fixes an issue with PatcherExtensions which had an NPE when trying to access the logger field of the patcher.

### CODE REVIEW

**Comment by Vendicated** [comment]
`name` is deprecated

**Comment by Vendicated** [comment]
moving these fields inside init seems like a bad idea. Some plugins may have something like
```kt
class MyPlugin : Plugin() {
    val patches = Patches(patcher)
}
```
With your changes this would lead to NPE

**Comment by zt64** [comment]
I'm unsure how else to do it without using the deprecated `name` property then

**Comment by Vendicated** [comment]
you can't

**Comment by zt64** [comment]
> you can't

<:guh:880053575340933151>

**Comment by wingio** [comment]
<:trollely:916000880724172860>

**Pull request closed without merging**
