### PR TITLE
Enable experiment for editing server profile, banner, and bio by default

### PR DESCRIPTION
**Pull request by ScrubN**
I was inspired by e63cc053bcfa1cf012375587a13f9481bb185f6a to check out some other experiments and found an experiment that allows me to edit my server pfp/banner/bio, so it would be nice to have it enabled by default. I don't have building setup, but this should work.

### CODE REVIEW

**Review by Juby210 — APPROVED** [review]

**Comment by katherinehackworth** [comment]
gives a permission error with nitro classic btw, had to revert

**Comment by Juby210** [comment]
image

custom server profiles are only option on normal nitro so obviously it won't work without it

**Comment by ScrubN** [comment]
So maybe instead of always enabling the experiment, perhaps it could be selectively enabled depending on the current nitro status of the user for those unaware of the perks included with their plan?

It would mean a bit more code to maintain though.

**Comment by ScrubN** [comment]
I just tested with an account that does not have nitro and I cannot update the server nickname. Either a nitro status check needs to be implemented or the PR needs to be reverted. Apologies for not testing the experiment with all cases.

**Pull request merged**
